packages:
  - packages/**
  - playground/*
  - website/**

ignoredBuiltDependencies:
  - core-js

onlyBuiltDependencies:
  - esbuild
  - vue-demi

overrides:
  lightningcss: ^1.31.0

patchedDependencies:
  '@zag-js/toast@1.41.1': patches/@zag-js__toast@1.41.1.patch

shellEmulator: true

trustPolicy: no-downgrade

trustPolicyExclude:
  - chokidar@4.0.3
  - vite@6.4.1
  - semver@5.7.2
  - semver@6.3.1

trustPolicyIgnoreAfter: 1051200
